@startuml
class Printer {
  +print(int): String
  +print(String): String
  +mode(): String
}
class ColorPrinter {
  +mode(): String
}
Printer <|-- ColorPrinter
note right of Printer
Overload: print(int), print(String)
Override: ColorPrinter.mode()
end note
@enduml

