@startuml
interface PaymentStrategy {
  +pay(amount: double): String
}
class CardPayment
class BlikPayment
class Checkout {
  -paymentStrategy: PaymentStrategy
}
PaymentStrategy <|.. CardPayment
PaymentStrategy <|.. BlikPayment
Checkout --> PaymentStrategy
@enduml

